name: SystemC CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Install dependencies (SystemC, build-essential, etc.)
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake g++ libboost-all-dev
          git clone https://github.com/accellera-official/systemc.git
          cd systemc
          mkdir objdir && cd objdir
          ../configure --prefix=$HOME/systemc
          make -j4
          make install

      # Step 3: Compile the hello.cpp file (SystemC code)
      - name: Compile SystemC code
        run: |
          g++ -I$HOME/systemc/include -L$HOME/systemc/lib -o hello hello.cpp -lsystemc -lm

      # Step 4: Run the compiled executable
      - name: Run the executable
        run: |
          ./hello
