name: Basic SystemC CI/CD Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake g++ libboost-all-dev

      - name: Download and install SystemC
        run: |
          git clone https://github.com/accellera-official/systemc.git
          cd systemc
          mkdir build && cd build
          cmake .. -DCMAKE_INSTALL_PREFIX=$HOME/systemc-install
          make -j$(nproc)
          make install

      - name: Compile helloC.cpp manually
        run: |
          g++ -I$HOME/systemc-install/include \
              -L$HOME/systemc-install/lib \
              helloC.cpp -o helloC -lsystemc -lm

      - name: Run SystemC program
        run: ./helloC
