name: SystemC CI/CD Workflows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake g++ libboost-all-dev

      - name: Download and build SystemC
        run: |
          git clone https://github.com/accellera-official/systemc.git
          cd systemc
          mkdir objdir && cd objdir
          ../configure --prefix=$HOME/systemc-install
          make -j$(nproc)
          make install

      - name: Compile SystemC hello.cpp
        run: |
          g++ -I$HOME/systemc-install/include \
              -L$HOME/systemc-install/lib-linux64 \
              hello.cpp -o hello -lsystemc -lm

      - name: Run SystemC executable
        run: ./hello
